import "./globals.css";
import Script from 'next/script'

export const metadata = {
  title: "Buchhaltung Claudia Riba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body className="bg-white text-secondary min-h-screen">
        <main className="">{children}</main>
        <Script
           src="https://stats.cloud.schman.dev/script.js"
           data-website-id="14bf1924-0058-4002-9ef6-518c347caf82"
           defer
           strategy="afterInteractive"
         />
      </body>
    </html>
  );
}
